name: Build and Deploy

on:
  push:
    branches: [main, master]

jobs:

  build:

    runs-on: windows-latest
    steps:

      - name: Setup repo
        uses: actions/checkout@v2.3.1

      - name: setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Build
        working-directory: ./frontend/app
        run: |
          deno run --allow-run --allow-read https://deno.land/x/snel/install.ts
          trex run build
          
      - name: Dir
        run: dir ./frontend
        
     
